[package]
name = "calculator_with_data_acc_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "1.18.0"

[lib]
crate-type = ["cdylib", "lib"]